[package]
name = "nsncd"
version = "1.2.1"
authors = [
    "Ben Linsay <ben.linsay@twosigma.com>",
    "Geoffrey Thomas <geoffrey.thomas@twosigma.com>",
    "Leif Walsh <leif.walsh@twosigma.com>",
]
edition = "2018"
description = "The name service non-caching daemon"
readme = "README.md"
repository = "https://github.com/twosigma/nsncd"
license = "Apache-2.0"

[dependencies]
anyhow = "^1.0"
atoi = "^0.4"
slog = "^2.7"
slog-async = "^2.7"
slog-term = "^2.8"
crossbeam-channel = "^0.5"
# Hold at 0.21 - 0.22 MSRV is greater than Debian stretch
nix = "^0.21.2"
num-derive = "^0.3"
num-traits = "^0.2"
tokio = { version = "^1.13", features = ["full"]}

[dev-dependencies]
criterion = "^0.3"

[[bench]]
name = "user"
harness = false
